#!/bin/bash

echo "Add some scripts to stop hook"


# The logic to stop your application should be put in this script.

#kill `ps -ef | grep test.py | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1

exit 0

